name: Static Application Security Testing
run-name: vibecoder is running a static code analyzer
on: [push]

jobs:
  Static-application-Security-Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - run: ./gradlew check